export default {
  PASSWORD_INVALID: 'PASSWORD_INVALID',
  EMPTY_NAME: 'EMPTY_NAME',
  CPF_INVALID: 'CPF_INVALID',
  ID_INVALID: 'ID_INVALID',
  NAME_CHARS_INVALID: 'NAME_CHARS_INVALID',
  BIG_NAME: 'BIG_NAME',
  NAME_WITHOUT_SURNAME: 'NAME_WITHOUT_SURNAME',
  SMALL_NAME: 'SMALL_NAME'
} as const